version: '3.9'
name: study-world
services:
  web:
    container_name: web
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network
    depends_on:
      - app

  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    image: study-world:latest
    ports:
      - "5000:5000"
    restart: always
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy
  
  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - app_network

  adminer:
    container_name: adminer
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    networks:
      - app_network
    depends_on:
      - db

networks:
  app_network:
    driver: bridge

